import type { VideoProject } from "@/lib/renderer";

/**
 * A dense, multi-act explainer of client–server architecture.
 * 10 seconds, 1920×1080, ~35 events across 5 layers.
 *
 * Acts:
 *   0–1.5s  Cold Open          – title + subtitle + decorative sweep
 *   1.5–3s  The Stacks         – client layers (left) + server layers (right)
 *   3–5s    The Request        – POST packet flies client → server
 *   4.5–6.5s Server Processing – validate → hash → store cascade
 *   6–8s    The Response       – 201 packet flies server → client
 *   7.5–9s  Full Picture       – overlay + round-trip labels
 *   8.5–10s Outro              – closing line + accent triangles
 */
export const bigDemoProject: VideoProject = {
  id: "big-demo-client-server",
  name: "Client–Server Architecture",
  width: 1920,
  height: 1080,
  duration: 10,
  events: [
    // ── Background ───────────────────────────────────────────────
    {
      id: "bg",
      type: "background",
      start: 0,
      end: 10,
      layer: 0,
      background: {
        kind: "gradient",
        from: "#020617",
        to: "#0c1425",
        angle: 160,
      },
    },

    // ── Act 1: Cold Open (0–1.5s) ────────────────────────────────
    {
      id: "title",
      type: "text",
      start: 0.1,
      end: 2.0,
      layer: 4,
      text: "How the Web Works",
      x: 460,
      y: 400,
      maxWidth: 1000,
      fontSize: 80,
      fontWeight: 800,
      color: "#f1f5f9",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 30, to: 0, easing: "easeOut" },
    },
    {
      id: "subtitle",
      type: "text",
      start: 0.5,
      end: 2.0,
      layer: 4,
      text: "Client → Server → Response",
      x: 620,
      y: 500,
      maxWidth: 680,
      fontSize: 32,
      fontWeight: 400,
      color: "rgb(148 163 184 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeInOut" },
    },
    {
      id: "deco-line",
      type: "shape",
      shapeType: "line",
      start: 0.3,
      end: 2.2,
      layer: 1,
      x1: 200,
      y1: 780,
      x2: 1720,
      y2: 780,
      stroke: "rgb(59 130 246 / 0.4)",
      lineWidth: 2,
      opacity: { from: 0, to: 0.7, easing: "linear" },
      translateX: { from: -100, to: 0, easing: "easeOut" },
    },

    // ── Act 2: The Stacks (1.5–3.0s) ────────────────────────────
    // CLIENT side (left)
    {
      id: "client-header",
      type: "text",
      start: 1.5,
      end: 9.5,
      layer: 4,
      text: "CLIENT",
      x: 240,
      y: 180,
      maxWidth: 300,
      fontSize: 18,
      fontWeight: 700,
      color: "rgb(96 165 250 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },
    {
      id: "browser-rect",
      type: "shape",
      shapeType: "rect",
      start: 1.6,
      end: 9.5,
      layer: 2,
      x: 140,
      y: 220,
      width: 400,
      height: 130,
      radius: 16,
      fill: "rgb(30 41 59 / 0.8)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 30, to: 0, easing: "easeOut" },
    },
    {
      id: "browser-label",
      type: "text",
      start: 1.7,
      end: 9.5,
      layer: 4,
      text: "Browser",
      x: 250,
      y: 265,
      maxWidth: 280,
      fontSize: 28,
      fontWeight: 600,
      color: "#e2e8f0",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 20, to: 0, easing: "easeOut" },
    },
    {
      id: "http-rect",
      type: "shape",
      shapeType: "rect",
      start: 1.8,
      end: 9.5,
      layer: 2,
      x: 140,
      y: 370,
      width: 400,
      height: 110,
      radius: 14,
      fill: "rgb(30 41 59 / 0.6)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 30, to: 0, easing: "easeOut" },
    },
    {
      id: "http-label",
      type: "text",
      start: 1.9,
      end: 9.5,
      layer: 4,
      text: "HTTP Layer",
      x: 245,
      y: 405,
      maxWidth: 260,
      fontSize: 24,
      fontWeight: 600,
      color: "rgb(203 213 225 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },
    {
      id: "network-rect",
      type: "shape",
      shapeType: "rect",
      start: 2.0,
      end: 9.5,
      layer: 2,
      x: 140,
      y: 500,
      width: 400,
      height: 110,
      radius: 14,
      fill: "rgb(30 41 59 / 0.45)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 30, to: 0, easing: "easeOut" },
    },
    {
      id: "network-label",
      type: "text",
      start: 2.1,
      end: 9.5,
      layer: 4,
      text: "Network",
      x: 255,
      y: 535,
      maxWidth: 260,
      fontSize: 24,
      fontWeight: 600,
      color: "rgb(203 213 225 / 0.7)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },

    // SERVER side (right)
    {
      id: "server-header",
      type: "text",
      start: 1.8,
      end: 9.5,
      layer: 4,
      text: "SERVER",
      x: 1490,
      y: 180,
      maxWidth: 300,
      fontSize: 18,
      fontWeight: 700,
      color: "rgb(52 211 153 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },
    {
      id: "api-rect",
      type: "shape",
      shapeType: "rect",
      start: 1.9,
      end: 9.5,
      layer: 2,
      x: 1380,
      y: 220,
      width: 400,
      height: 130,
      radius: 16,
      fill: "rgb(30 41 59 / 0.8)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 30, to: 0, easing: "easeOut" },
    },
    {
      id: "api-label",
      type: "text",
      start: 2.0,
      end: 9.5,
      layer: 4,
      text: "REST API",
      x: 1490,
      y: 265,
      maxWidth: 280,
      fontSize: 28,
      fontWeight: 600,
      color: "#e2e8f0",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 20, to: 0, easing: "easeOut" },
    },
    {
      id: "logic-rect",
      type: "shape",
      shapeType: "rect",
      start: 2.1,
      end: 9.5,
      layer: 2,
      x: 1380,
      y: 370,
      width: 400,
      height: 110,
      radius: 14,
      fill: "rgb(30 41 59 / 0.6)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 30, to: 0, easing: "easeOut" },
    },
    {
      id: "logic-label",
      type: "text",
      start: 2.2,
      end: 9.5,
      layer: 4,
      text: "Business Logic",
      x: 1440,
      y: 405,
      maxWidth: 300,
      fontSize: 24,
      fontWeight: 600,
      color: "rgb(203 213 225 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },
    {
      id: "db-rect",
      type: "shape",
      shapeType: "rect",
      start: 2.3,
      end: 9.5,
      layer: 2,
      x: 1380,
      y: 500,
      width: 400,
      height: 110,
      radius: 14,
      fill: "rgb(30 41 59 / 0.45)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 30, to: 0, easing: "easeOut" },
    },
    {
      id: "db-label",
      type: "text",
      start: 2.4,
      end: 9.5,
      layer: 4,
      text: "PostgreSQL",
      x: 1470,
      y: 535,
      maxWidth: 260,
      fontSize: 24,
      fontWeight: 600,
      color: "rgb(203 213 225 / 0.7)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },

    // Client–server vertical connector lines
    {
      id: "client-connector",
      type: "shape",
      shapeType: "line",
      start: 2.2,
      end: 9.5,
      layer: 1,
      x1: 340,
      y1: 350,
      x2: 340,
      y2: 500,
      stroke: "rgb(96 165 250 / 0.25)",
      lineWidth: 2,
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },
    {
      id: "server-connector",
      type: "shape",
      shapeType: "line",
      start: 2.5,
      end: 9.5,
      layer: 1,
      x1: 1580,
      y1: 350,
      x2: 1580,
      y2: 500,
      stroke: "rgb(52 211 153 / 0.25)",
      lineWidth: 2,
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },

    // ── Act 3: The Request (3.0–5.0s) ────────────────────────────
    {
      id: "req-label",
      type: "text",
      start: 3.0,
      end: 5.5,
      layer: 4,
      text: "POST /api/users",
      x: 750,
      y: 250,
      maxWidth: 420,
      fontSize: 26,
      fontWeight: 700,
      color: "rgb(96 165 250 / 1)",
      opacity: { from: 0, to: 1, easing: "easeIn" },
      translateY: { from: -15, to: 0, easing: "easeOut" },
    },
    {
      id: "req-line",
      type: "shape",
      shapeType: "line",
      start: 3.2,
      end: 5.5,
      layer: 3,
      x1: 540,
      y1: 285,
      x2: 1380,
      y2: 285,
      stroke: "rgb(96 165 250 / 0.6)",
      lineWidth: 3,
      opacity: { from: 0, to: 1, easing: "linear" },
      translateX: { from: -200, to: 0, easing: "easeOut" },
    },
    {
      id: "req-body",
      type: "text",
      start: 3.5,
      end: 5.2,
      layer: 4,
      text: "{ name, email, password }",
      x: 780,
      y: 300,
      maxWidth: 360,
      fontSize: 20,
      fontWeight: 500,
      color: "rgb(148 163 184 / 0.8)",
      opacity: { from: 0, to: 1, easing: "easeInOut" },
    },
    {
      id: "req-packet",
      type: "shape",
      shapeType: "circle",
      start: 3.3,
      end: 4.8,
      layer: 3,
      x: 960,
      y: 285,
      radius: 12,
      fill: "rgb(96 165 250 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateX: { from: -400, to: 400, easing: "linear" },
      scale: { from: 0.5, to: 1.2, easing: "easeInOut" },
    },

    // ── Act 4: Server Processing (4.5–6.5s) ──────────────────────
    {
      id: "processing-glow",
      type: "shape",
      shapeType: "rect",
      start: 4.5,
      end: 6.5,
      layer: 1,
      x: 1370,
      y: 210,
      width: 420,
      height: 410,
      radius: 20,
      fill: "rgb(52 211 153 / 0.06)",
      opacity: { from: 0, to: 0.8, easing: "easeIn" },
      scale: { from: 0.95, to: 1.02, easing: "bounce" },
    },
    {
      id: "step-validate",
      type: "text",
      start: 4.8,
      end: 6.5,
      layer: 4,
      text: "→ Validate",
      x: 1200,
      y: 275,
      maxWidth: 180,
      fontSize: 18,
      fontWeight: 600,
      color: "rgb(52 211 153 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateX: { from: -20, to: 0, easing: "easeOut" },
    },
    {
      id: "step-hash",
      type: "text",
      start: 5.1,
      end: 6.5,
      layer: 4,
      text: "→ Hash Password",
      x: 1200,
      y: 415,
      maxWidth: 200,
      fontSize: 18,
      fontWeight: 600,
      color: "rgb(52 211 153 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateX: { from: -20, to: 0, easing: "easeOut" },
    },
    {
      id: "step-store",
      type: "text",
      start: 5.4,
      end: 6.5,
      layer: 4,
      text: "→ INSERT INTO users",
      x: 1200,
      y: 545,
      maxWidth: 220,
      fontSize: 18,
      fontWeight: 600,
      color: "rgb(52 211 153 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateX: { from: -20, to: 0, easing: "easeOut" },
    },
    {
      id: "db-indicator",
      type: "shape",
      shapeType: "circle",
      start: 5.5,
      end: 7.0,
      layer: 3,
      x: 1680,
      y: 555,
      radius: 18,
      fill: "rgb(251 191 36 / 0.7)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      scale: { from: 0.6, to: 1, easing: "bounce" },
    },

    // ── Act 5: The Response (6.0–8.0s) ───────────────────────────
    {
      id: "res-label",
      type: "text",
      start: 6.0,
      end: 8.5,
      layer: 4,
      text: "201 Created",
      x: 810,
      y: 420,
      maxWidth: 340,
      fontSize: 26,
      fontWeight: 700,
      color: "rgb(52 211 153 / 1)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 15, to: 0, easing: "easeOut" },
    },
    {
      id: "res-line",
      type: "shape",
      shapeType: "line",
      start: 6.2,
      end: 8.5,
      layer: 3,
      x1: 1380,
      y1: 455,
      x2: 540,
      y2: 455,
      stroke: "rgb(52 211 153 / 0.6)",
      lineWidth: 3,
      opacity: { from: 0, to: 1, easing: "linear" },
      translateX: { from: 200, to: 0, easing: "easeOut" },
    },
    {
      id: "res-body",
      type: "text",
      start: 6.5,
      end: 8.2,
      layer: 4,
      text: '{ id: 42, status: "ok" }',
      x: 770,
      y: 470,
      maxWidth: 380,
      fontSize: 20,
      fontWeight: 500,
      color: "rgb(148 163 184 / 0.8)",
      opacity: { from: 0, to: 1, easing: "easeInOut" },
    },
    {
      id: "res-packet",
      type: "shape",
      shapeType: "circle",
      start: 6.3,
      end: 7.8,
      layer: 3,
      x: 960,
      y: 455,
      radius: 12,
      fill: "rgb(52 211 153 / 0.9)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateX: { from: 400, to: -400, easing: "linear" },
      scale: { from: 0.5, to: 1.2, easing: "easeInOut" },
    },

    // ── Act 6: Full Picture (7.5–9.0s) ───────────────────────────
    {
      id: "roundtrip-overlay",
      type: "shape",
      shapeType: "rect",
      start: 7.5,
      end: 9.5,
      layer: 1,
      x: 100,
      y: 160,
      width: 1720,
      height: 500,
      radius: 24,
      fill: "rgb(15 23 42 / 0.25)",
      opacity: { from: 0, to: 0.5, easing: "easeInOut" },
    },
    {
      id: "roundtrip-req-label",
      type: "text",
      start: 7.8,
      end: 9.5,
      layer: 4,
      text: "Request →",
      x: 830,
      y: 240,
      maxWidth: 260,
      fontSize: 22,
      fontWeight: 600,
      color: "rgb(96 165 250 / 0.8)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },
    {
      id: "roundtrip-res-label",
      type: "text",
      start: 8.0,
      end: 9.5,
      layer: 4,
      text: "← Response",
      x: 830,
      y: 490,
      maxWidth: 260,
      fontSize: 22,
      fontWeight: 600,
      color: "rgb(52 211 153 / 0.8)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },
    {
      id: "latency-label",
      type: "text",
      start: 8.2,
      end: 9.5,
      layer: 4,
      text: "~200ms round trip",
      x: 820,
      y: 365,
      maxWidth: 280,
      fontSize: 18,
      fontWeight: 500,
      color: "rgb(251 191 36 / 0.8)",
      opacity: { from: 0, to: 1, easing: "easeInOut" },
    },

    // ── Act 7: Outro (8.5–10s) ───────────────────────────────────
    {
      id: "closing-line",
      type: "text",
      start: 8.8,
      end: 10,
      layer: 4,
      text: "Every click. Every scroll. Every tap.",
      x: 520,
      y: 800,
      maxWidth: 880,
      fontSize: 40,
      fontWeight: 700,
      color: "#f1f5f9",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 20, to: 0, easing: "easeOut" },
    },
    {
      id: "accent-tri-left",
      type: "shape",
      shapeType: "triangle",
      start: 9.0,
      end: 10,
      layer: 1,
      x: 40,
      y: 900,
      width: 100,
      height: 90,
      fill: "rgb(59 130 246 / 0.5)",
      opacity: { from: 0, to: 0.7, easing: "easeOut" },
      rotate: { from: -15, to: 0, easing: "easeOut" },
    },
    {
      id: "accent-tri-right",
      type: "shape",
      shapeType: "triangle",
      start: 9.1,
      end: 10,
      layer: 1,
      x: 1780,
      y: 900,
      width: 100,
      height: 90,
      fill: "rgb(52 211 153 / 0.5)",
      opacity: { from: 0, to: 0.7, easing: "easeOut" },
      rotate: { from: 15, to: 0, easing: "easeOut" },
    },
  ],
};
