import type { VideoProject } from "@/lib/renderer";

export const demoProject: VideoProject = {
  id: "demo-launch-loop",
  name: "Launch Loop",
  width: 1920,
  height: 1080,
  duration: 5,
  events: [
    {
      id: "background",
      type: "background",
      start: 0,
      end: 5,
      layer: 0,
      background: {
        kind: "gradient",
        from: "#020617",
        to: "#1d4ed8",
        angle: 30,
      },
    },
    {
      id: "panel",
      type: "shape",
      shapeType: "rect",
      start: 0.35,
      end: 4.8,
      layer: 1,
      x: 168,
      y: 184,
      width: 840,
      height: 480,
      radius: 56,
      fill: "rgb(15 23 42 / 0.66)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 60, to: 0, easing: "easeOut" },
    },
    {
      id: "accent-circle",
      type: "shape",
      shapeType: "circle",
      start: 0.55,
      end: 4.6,
      layer: 1,
      x: 1520,
      y: 340,
      radius: 184,
      fill: "rgb(45 212 191 / 0.9)",
      opacity: { from: 0, to: 0.95, easing: "easeOut" },
      scale: { from: 0.6, to: 1, easing: "bounce" },
    },
    {
      id: "slash",
      type: "shape",
      shapeType: "line",
      start: 1.1,
      end: 4.5,
      layer: 2,
      x1: 1100,
      y1: 780,
      x2: 1720,
      y2: 216,
      stroke: "rgb(248 250 252 / 0.84)",
      lineWidth: 28,
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },
    {
      id: "title",
      type: "text",
      start: 0.2,
      end: 2.8,
      layer: 3,
      text: "Launch your next story in motion",
      x: 220,
      y: 252,
      maxWidth: 680,
      color: "#f8fafc",
      fontSize: 84,
      fontWeight: 700,
      lineHeight: 92,
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 56, to: 0, easing: "easeOut" },
    },
    {
      id: "subtitle",
      type: "text",
      start: 1.35,
      end: 4.8,
      layer: 3,
      text: "Prompt. Preview. Export. All from one compact studio flow.",
      x: 220,
      y: 564,
      maxWidth: 720,
      color: "rgb(191 219 254 / 0.94)",
      fontSize: 44,
      fontWeight: 500,
      lineHeight: 60,
      opacity: { from: 0, to: 1, easing: "easeInOut" },
      translateY: { from: 36, to: 0, easing: "easeOut" },
    },
    {
      id: "tag",
      type: "shape",
      shapeType: "triangle",
      start: 2.1,
      end: 5,
      layer: 2,
      x: 1380,
      y: 660,
      width: 240,
      height: 220,
      fill: "rgb(37 99 235 / 0.85)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      rotate: { from: -10, to: 0, easing: "easeOut" },
    },
    {
      id: "caption",
      type: "text",
      start: 2.45,
      end: 5,
      layer: 3,
      text: "Canvas-ready previews",
      x: 1180,
      y: 760,
      maxWidth: 440,
      color: "#f8fafc",
      fontSize: 52,
      fontWeight: 700,
      opacity: { from: 0, to: 1, easing: "easeInOut" },
      scale: { from: 0.92, to: 1, easing: "bounce" },
    },
  ],
};
