import type { VideoProject } from "@/lib/canvas/project";

export const demoProject: VideoProject = {
  id: "demo-launch-loop",
  name: "Launch Loop",
  width: 960,
  height: 540,
  duration: 5,
  events: [
    {
      id: "background",
      type: "background",
      start: 0,
      end: 5,
      layer: 0,
      background: {
        kind: "gradient",
        from: "#020617",
        to: "#1d4ed8",
        angle: 30,
      },
    },
    {
      id: "panel",
      type: "shape",
      shapeType: "rect",
      start: 0.35,
      end: 4.8,
      layer: 1,
      x: 84,
      y: 92,
      width: 420,
      height: 240,
      radius: 28,
      fill: "rgb(15 23 42 / 0.66)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 30, to: 0, easing: "easeOut" },
    },
    {
      id: "accent-circle",
      type: "shape",
      shapeType: "circle",
      start: 0.55,
      end: 4.6,
      layer: 1,
      x: 760,
      y: 170,
      radius: 92,
      fill: "rgb(45 212 191 / 0.9)",
      opacity: { from: 0, to: 0.95, easing: "easeOut" },
      scale: { from: 0.6, to: 1, easing: "bounce" },
    },
    {
      id: "slash",
      type: "shape",
      shapeType: "line",
      start: 1.1,
      end: 4.5,
      layer: 2,
      x1: 550,
      y1: 390,
      x2: 860,
      y2: 108,
      stroke: "rgb(248 250 252 / 0.84)",
      lineWidth: 14,
      opacity: { from: 0, to: 1, easing: "easeOut" },
    },
    {
      id: "title",
      type: "text",
      start: 0.2,
      end: 2.8,
      layer: 3,
      text: "Launch your next story in motion",
      x: 110,
      y: 126,
      maxWidth: 340,
      color: "#f8fafc",
      fontSize: 42,
      fontWeight: 700,
      lineHeight: 46,
      opacity: { from: 0, to: 1, easing: "easeOut" },
      translateY: { from: 28, to: 0, easing: "easeOut" },
    },
    {
      id: "subtitle",
      type: "text",
      start: 1.35,
      end: 4.8,
      layer: 3,
      text: "Prompt. Preview. Export. All from one compact studio flow.",
      x: 110,
      y: 282,
      maxWidth: 360,
      color: "rgb(191 219 254 / 0.94)",
      fontSize: 22,
      fontWeight: 500,
      lineHeight: 30,
      opacity: { from: 0, to: 1, easing: "easeInOut" },
      translateY: { from: 18, to: 0, easing: "easeOut" },
    },
    {
      id: "tag",
      type: "shape",
      shapeType: "triangle",
      start: 2.1,
      end: 5,
      layer: 2,
      x: 690,
      y: 330,
      width: 120,
      height: 110,
      fill: "rgb(37 99 235 / 0.85)",
      opacity: { from: 0, to: 1, easing: "easeOut" },
      rotate: { from: -10, to: 0, easing: "easeOut" },
    },
    {
      id: "caption",
      type: "text",
      start: 2.45,
      end: 5,
      layer: 3,
      text: "Canvas-ready previews",
      x: 590,
      y: 380,
      maxWidth: 220,
      color: "#f8fafc",
      fontSize: 26,
      fontWeight: 700,
      opacity: { from: 0, to: 1, easing: "easeInOut" },
      scale: { from: 0.92, to: 1, easing: "bounce" },
    },
  ],
};
