import type { VideoProject } from "@/lib/renderer";

/**
 * Returns a deterministic seed project used by stub API routes until
 * Phase 6A wires in `buildProjectFromBrief`.
 */
export function createSeedProject(name: string, duration: number): VideoProject {
  const d = duration;
  return {
    id: `seed-${Date.now()}`,
    name,
    width: 1920,
    height: 1080,
    duration: d,
    events: [
      {
        id: "bg",
        type: "background",
        start: 0,
        end: d,
        layer: 0,
        background: { kind: "gradient", from: "#0f172a", to: "#1e3a5f", angle: 145 },
      },
      {
        id: "accent-left",
        type: "shape",
        shapeType: "circle",
        start: 0,
        end: d,
        layer: 1,
        x: 200,
        y: 540,
        radius: 260,
        fill: "rgb(99 102 241 / 0.18)",
        opacity: { from: 0, to: 1, easing: "easeOut" },
        scale: { from: 0.6, to: 1, easing: "easeOut" },
      },
      {
        id: "accent-right",
        type: "shape",
        shapeType: "circle",
        start: 0.2,
        end: d,
        layer: 1,
        x: 1720,
        y: 540,
        radius: 320,
        fill: "rgb(45 212 191 / 0.14)",
        opacity: { from: 0, to: 1, easing: "easeOut" },
        scale: { from: 0.6, to: 1, easing: "easeInOut" },
      },
      {
        id: "divider",
        type: "shape",
        shapeType: "line",
        start: 0.4,
        end: d,
        layer: 2,
        x1: 960,
        y1: 200,
        x2: 960,
        y2: 880,
        stroke: "rgb(148 163 184 / 0.25)",
        lineWidth: 2,
        lineDash: [12, 8],
        opacity: { from: 0, to: 1, easing: "easeOut" },
      },
      {
        id: "title",
        type: "text",
        start: 0.1,
        end: d,
        layer: 3,
        text: name,
        x: 120,
        y: 400,
        maxWidth: 780,
        color: "#f8fafc",
        fontSize: 96,
        fontWeight: 700,
        lineHeight: 108,
        opacity: { from: 0, to: 1, easing: "easeOut" },
        translateY: { from: 48, to: 0, easing: "easeOut" },
      },
      {
        id: "subtitle",
        type: "text",
        start: 0.5,
        end: d,
        layer: 3,
        text: "Generated with VideoGPT",
        x: 120,
        y: 640,
        maxWidth: 720,
        color: "rgb(148 163 184 / 0.9)",
        fontSize: 48,
        fontWeight: 400,
        lineHeight: 64,
        opacity: { from: 0, to: 1, easing: "easeInOut" },
        translateY: { from: 32, to: 0, easing: "easeOut" },
      },
    ],
  };
}
