"use client";

import { useEffect, useRef, useState, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { useStore } from "@/lib/store";
import { TopBar } from "@/components/layout/TopBar";
import { renderProjectFrame } from "@/lib/renderer";
import { visibleEvents } from "@/lib/renderer/visibleEvents";

// ── Frame Thumbnail Component ────────────────────────────────────────────────
function FrameThumbnail({
  project,
  time,
  onClick,
  active,
}: {
  project: any;
  time: number;
  onClick: () => void;
  active: boolean;
}) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          observer.disconnect();
        }
      },
      {
        rootMargin: "200px",
      }
    );

    observer.observe(canvas);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !project || !isVisible) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    // Clear and render static frame at specific timestamp
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    renderProjectFrame(ctx, project, time);
  }, [project, time, isVisible]);

  return (
    <button
      type="button"
      onClick={onClick}
      className={`group flex flex-col gap-1.5 p-2 rounded-xl border text-left transition-all cursor-pointer ${active
          ? "border-foreground bg-foreground/5 shadow-sm font-semibold"
          : "border-border hover:border-foreground/30 hover:bg-foreground/1"
        }`}
    >
      <span className="text-[10px] font-mono text-muted-foreground group-hover:text-foreground">
        {time.toFixed(2)}s
      </span>
      <div className="aspect-video w-full rounded-lg overflow-hidden border border-border/60 bg-black/10">
        <canvas
          ref={canvasRef}
          width={project.width || 800}
          height={project.height || 450}
          className="w-full h-full object-cover"
        />
      </div>
    </button>
  );
}

// ── Interactive Rendering Explanation Component ────────────────────────────────
function RenderingExplanation({ brief, project, duration }: { brief: any; project: any; duration: number }) {
  if (!brief || !project) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-6 text-center text-muted-foreground italic text-xs">
        No diagnostics or compiled project structure available.
      </div>
    );
  }

  const isTwoColumn = brief.layout === "two-column";

  const getEventTiming = (idPrefix: string) => {
    const ev = project.events.find((e: any) => e.id === idPrefix || e.id?.startsWith(idPrefix));
    if (!ev) return "Inactive";
    return `${ev.start.toFixed(1)}s – ${ev.end.toFixed(1)}s`;
  };

  return (
    <div className="flex-1 overflow-y-auto pr-1 space-y-6 text-xs text-muted-foreground select-text">
      {/* Overview Banner */}
      <div className="p-4 rounded-xl border border-border/60 bg-foreground/1 space-y-2">
        <div className="flex items-center justify-between">
          <span className="font-bold text-foreground text-sm">Brief Expansion Engine</span>
          <span className={`px-2.5 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-wider ${isTwoColumn ? 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/20' : 'bg-amber-500/10 text-amber-400 border border-amber-500/20'}`}>
            {brief.layout || "single-column"}
          </span>
        </div>
        <p className="text-[11px] leading-relaxed">
          The layout is dynamically generated by translating high-level, creative parameters from the AI Brief into pixel coordinates and absolute timestamps. Creative decisions are driven entirely by the AI.
        </p>
      </div>

      {/* Timing Act Breakdown */}
      <div className="space-y-3">
        <h4 className="text-[10px] font-bold uppercase tracking-wider text-foreground">Timeline Act Boundaries</h4>
        <p className="text-[11px] leading-relaxed">
          AI weights <code className="bg-background px-1.5 py-0.5 rounded font-mono text-foreground">{JSON.stringify(brief.actWeights || [1, 1.5, 1, 1.5, 1])}</code> scale act timings proportionally. Active time-ranges extracted from compiled elements:
        </p>
        <div className="grid grid-cols-5 gap-1.5 font-mono text-[9px]">
          <div className="p-2.5 bg-background border border-border/40 rounded-lg text-center flex flex-col justify-between min-h-[60px]">
            <span className="font-bold text-foreground">Act 1: Title</span>
            <span className="text-[9px] text-muted-foreground/80 mt-1 bg-foreground/3 rounded py-0.5">{getEventTiming("title")}</span>
          </div>
          <div className="p-2.5 bg-background border border-border/40 rounded-lg text-center flex flex-col justify-between min-h-[60px]">
            <span className="font-bold text-foreground">Act 2: Stacks</span>
            <span className="text-[9px] text-muted-foreground/80 mt-1 bg-foreground/3 rounded py-0.5">{getEventTiming("left-header")}</span>
          </div>
          <div className="p-2.5 bg-background border border-border/40 rounded-lg text-center flex flex-col justify-between min-h-[60px]">
            <span className="font-bold text-foreground">Act 3: Flow Out</span>
            <span className="text-[9px] text-muted-foreground/80 mt-1 bg-foreground/3 rounded py-0.5">{getEventTiming("req-packet")}</span>
          </div>
          <div className="p-2.5 bg-background border border-border/40 rounded-lg text-center flex flex-col justify-between min-h-[60px]">
            <span className="font-bold text-foreground">Act 4: Process</span>
            <span className="text-[9px] text-muted-foreground/80 mt-1 bg-foreground/3 rounded py-0.5">{getEventTiming("step-progress-")}</span>
          </div>
          <div className="p-2.5 bg-background border border-border/40 rounded-lg text-center flex flex-col justify-between min-h-[60px]">
            <span className="font-bold text-foreground">Act 5: Outro</span>
            <span className="text-[9px] text-muted-foreground/80 mt-1 bg-foreground/3 rounded py-0.5">{getEventTiming("closing-line")}</span>
          </div>
        </div>
      </div>

      {/* Layer Stack Hierarchy */}
      <div className="space-y-3">
        <h4 className="text-[10px] font-bold uppercase tracking-wider text-foreground">Canvas Layer Hierarchy</h4>
        <div className="space-y-1 bg-background/40 p-2 rounded-xl border border-border/40 font-mono text-[9px]">
          <div className="p-1.5 bg-foreground/5 rounded border border-border/20 flex justify-between">
            <span className="text-foreground font-semibold">Layer 5 (Top): Text & Labels</span>
            <span>Title, headers, outro, processing details</span>
          </div>
          <div className="p-1.5 bg-foreground/5 rounded border border-border/20 flex justify-between">
            <span className="text-foreground font-semibold">Layer 4: Tech Icons & Badges</span>
            <span>Row icons, row labels, protocol annotation cards</span>
          </div>
          <div className="p-1.5 bg-foreground/5 rounded border border-border/20 flex justify-between">
            <span className="text-foreground font-semibold">Layer 3: Active Packets & Rings</span>
            <span>Flowing request/response particles, pulse rings, progress bar fills</span>
          </div>
          <div className="p-1.5 bg-foreground/5 rounded border border-border/20 flex justify-between">
            <span className="text-foreground font-semibold">Layer 2: Stack Card Rectangles</span>
            <span>Row backgrounds, connector lines, request trails</span>
          </div>
          <div className="p-1.5 bg-foreground/5 rounded border border-border/20 flex justify-between">
            <span className="text-foreground font-semibold">Layer 1: Accent Lines & Particles</span>
            <span>Ambient particle systems, central divider, decoration limits</span>
          </div>
          <div className="p-1.5 bg-foreground/5 rounded border border-border/20 flex justify-between">
            <span className="text-foreground font-semibold">Layer 0 (Base): Background Canvas</span>
            <span>Vibrant Solid or Gradient color fill</span>
          </div>
        </div>
      </div>

      {/* Attribute Mapping Table */}
      <div className="space-y-2">
        <h4 className="text-[10px] font-bold uppercase tracking-wider text-foreground">AI Parameter Mapping Specifications</h4>
        <div className="border border-border/60 rounded-xl overflow-hidden bg-background/30">
          <table className="w-full text-left border-collapse text-[11px]">
            <thead>
              <tr className="border-b border-border/65 bg-background/60 text-foreground font-bold">
                <th className="p-2">Property</th>
                <th className="p-2 w-1/3">Current Brief Value</th>
                <th className="p-2">Canvas Compilation & Drawing Rules</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/40 font-normal">
              <tr className="hover:bg-foreground/1">
                <td className="p-2 font-mono font-semibold text-foreground">title</td>
                <td className="p-2 italic text-foreground">"{brief.title}"</td>
                <td className="p-2 leading-relaxed">
                  Drawn on Layer 5 (ID: <code className="bg-background px-1 rounded text-foreground font-mono">title</code>). Formatted using sizing directive <code className="bg-background px-1 rounded font-mono">{brief.titleSize || "large"}</code> and aligned <code className="bg-background px-1 rounded font-mono">{brief.titleAlign || "left"}</code>.
                </td>
              </tr>
              <tr className="hover:bg-foreground/1">
                <td className="p-2 font-mono font-semibold text-foreground">palette</td>
                <td className="p-2 font-mono text-foreground">"{brief.palette}"</td>
                <td className="p-2 leading-relaxed">
                  Resolves background fills (Layer 0 ID: <code className="bg-background px-1 rounded text-foreground font-mono">bg</code>) and shapes styling via accent & surface values. Injected overrides are applied to accents or panels dynamically.
                </td>
              </tr>
              <tr className="hover:bg-foreground/1">
                <td className="p-2 font-mono font-semibold text-foreground">style</td>
                <td className="p-2 font-mono text-foreground">"{brief.style}"</td>
                <td className="p-2 leading-relaxed">
                  Governs border radius, outline thicknesses, line dashed segments, and default easing functions.
                </td>
              </tr>
              <tr className="hover:bg-foreground/1">
                <td className="p-2 font-mono font-semibold text-foreground">entryAnimation</td>
                <td className="p-2 font-mono text-foreground">"{brief.entryAnimation || "slide-up"}"</td>
                <td className="p-2 leading-relaxed">
                  Drives translation vectors (e.g. translateY or scale bounce) from start position to final canvas layout configuration.
                </td>
              </tr>
              {isTwoColumn ? (
                <>
                  <tr className="hover:bg-foreground/1">
                    <td className="p-2 font-mono font-semibold text-foreground">leftRows / rightRows</td>
                    <td className="p-2 leading-relaxed text-foreground">
                      <div>Left ({brief.leftRows?.length || 0}): {brief.leftRows?.join(", ")}</div>
                      <div className="mt-1">Right ({brief.rightRows?.length || 0}): {brief.rightRows?.join(", ")}</div>
                    </td>
                    <td className="p-2 leading-relaxed">
                      Compiles into rectangle cards on Layer 2 and label texts on Layer 4. Icons correspond to keyword matches or fall back to seeded random choices.
                    </td>
                  </tr>
                  <tr className="hover:bg-foreground/1">
                    <td className="p-2 font-mono font-semibold text-foreground">emphasizeLeft / emphasizeRight</td>
                    <td className="p-2 font-mono text-foreground">
                      L: {brief.emphasizeLeft ?? 0}, R: {brief.emphasizeRight ?? 0}
                    </td>
                    <td className="p-2 leading-relaxed">
                      Indexes receive highlight focus: accent colors, thicker borders (1.5x), and glow shadow blurs.
                    </td>
                  </tr>
                  <tr className="hover:bg-foreground/1">
                    <td className="p-2 font-mono font-semibold text-foreground">flow</td>
                    <td className="p-2 font-mono text-foreground font-semibold">
                      {brief.flow ? "Enabled" : "Disabled"}
                    </td>
                    <td className="p-2 leading-relaxed">
                      {brief.flow ? (
                        <span>
                          Triggers request/response packets moving along curves, progress bars, processing steps with text annotations, and a roundtrip timeline overlay during Acts 3–5.
                        </span>
                      ) : (
                        <span>Static column cards display with no animated data transaction vectors.</span>
                      )}
                    </td>
                  </tr>
                </>
              ) : (
                <>
                  <tr className="hover:bg-foreground/1">
                    <td className="p-2 font-mono font-semibold text-foreground">blocks</td>
                    <td className="p-2 text-foreground">
                      {brief.blocks?.length || 0} vertical elements
                    </td>
                    <td className="p-2 leading-relaxed">
                      Generates content blocks stacked vertically with descriptions and icon illustrations.
                    </td>
                  </tr>
                  <tr className="hover:bg-foreground/1">
                    <td className="p-2 font-mono font-semibold text-foreground">blockStyle</td>
                    <td className="p-2 font-mono text-foreground">"{brief.blockStyle || "stacked"}"</td>
                    <td className="p-2 leading-relaxed">
                      Determines outline card bounds (<code className="bg-background px-1 rounded text-foreground font-mono">cards</code>), vertical dots (<code className="bg-background px-1 rounded text-foreground font-mono">timeline</code>), or serial counts (<code className="bg-background px-1 rounded text-foreground font-mono">numbered</code>).
                    </td>
                  </tr>
                </>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// ── Advanced Mode Diagnostics Workspace ───────────────────────────────────────
function AdvanceWorkspace() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const sessionId = searchParams.get("sessionId");
  const messageId = searchParams.get("messageId");

  const sessions = useStore((s) => s.sessions);
  const activeSessionId = useStore((s) => s.activeSessionId);

  // Determine target session and message
  const targetSessionId = sessionId || activeSessionId;
  const session = sessions.find((s) => s.id === targetSessionId);
  const message = messageId
    ? session?.messages.find((m) => m.id === messageId)
    : session?.messages[session.messages.length - 1]; // fallback to latest assistant msg

  const project = message?.project;
  const brief = message?.brief;

  // State
  const [activeTab, setActiveTab] = useState<"metadata" | "raw" | "brief" | "project" | "explanation">("metadata");
  const [selectedTime, setSelectedTime] = useState<number>(0);
  const [copied, setCopied] = useState(false);

  const focusCanvasRef = useRef<HTMLCanvasElement | null>(null);

  // Redirect if missing critical details
  useEffect(() => {
    if (!targetSessionId || !messageId) {
      router.replace("/dev");
    }
  }, [targetSessionId, messageId, router]);

  // Sync rendering on main focus canvas
  useEffect(() => {
    const canvas = focusCanvasRef.current;
    if (!canvas || !project) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    renderProjectFrame(ctx, project, selectedTime);
  }, [project, selectedTime]);

  if (!session || !message || !project) {
    return (
      <div className="flex h-screen flex-col items-center justify-center p-6 text-center">
        <p className="text-sm text-muted-foreground animate-pulse">Loading diagnostics data...</p>
      </div>
    );
  }

  // Generate frames at native 30 FPS
  const fps = 30;
  const duration = project.duration || 5;
  const totalFrames = Math.ceil(duration * fps);
  const frameTimes = Array.from({ length: totalFrames + 1 }, (_, i) => {
    if (i === totalFrames) return duration;
    return i / fps;
  });

  // Fetch active events at selected time
  const activeEvents = visibleEvents(project, selectedTime);

  // Copy code utility
  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getCodeContent = () => {
    if (activeTab === "raw") return JSON.stringify(message.rawBrief || { error: "No raw AI response cached for this historical session. Try generating or modifying a project in the workspace to view real-time raw response outputs." }, null, 2);
    if (activeTab === "brief") return JSON.stringify(brief || { error: "No Brief generated for this frame version" }, null, 2);
    if (activeTab === "project") return JSON.stringify(project, null, 2);
    return "";
  };

  const isJsonTab = activeTab === "raw" || activeTab === "brief" || activeTab === "project";

  return (
    <div className="flex flex-1 flex-col overflow-hidden h-full">
      <TopBar
        title="Diagnostics"
        actions={
          <button
            type="button"
            onClick={() => router.push("/dev")}
            className="rounded-full border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition-all duration-150 hover:bg-foreground/3 hover:text-foreground active:scale-95 cursor-pointer"
          >
            ← Back to Dev
          </button>
        }
      />

      <main className="mt-6 flex flex-1 overflow-hidden gap-6 h-[calc(100vh-140px)]">
        {/* ── Left Column: Data Inspector ─────────────────────────────── */}
        <section className="w-1/2 flex flex-col h-full border border-border bg-surface-raised rounded-xl p-5 overflow-hidden">
          <div className="flex items-center justify-between border-b border-border/60 pb-3 mb-4 gap-2 flex-wrap">
            <div className="flex gap-1 bg-background p-0.5 rounded-lg border border-border/80 flex-wrap">
              {(["metadata", "raw", "brief", "project", "explanation"] as const).map((tab) => (
                <button
                  key={tab}
                  type="button"
                  onClick={() => setActiveTab(tab)}
                  className={`px-2 py-1 text-[11px] font-bold rounded-md transition-all cursor-pointer ${activeTab === tab
                      ? "bg-surface-raised text-foreground shadow-xs border border-border/10"
                      : "text-muted-foreground hover:text-foreground"
                    }`}
                >
                  {tab === "metadata"
                    ? "Metadata"
                    : tab === "raw"
                    ? "Raw AI Response"
                    : tab === "brief"
                    ? "AI Brief"
                    : tab === "project"
                    ? "Timeline JSON"
                    : "Rendering Flow"}
                </button>
              ))}
            </div>

            {isJsonTab && (
              <button
                type="button"
                onClick={() => handleCopy(getCodeContent())}
                className="rounded-lg border border-border px-2.5 py-1 text-xs font-bold text-muted-foreground hover:bg-foreground/5 hover:text-foreground transition-all duration-150 cursor-pointer"
              >
                {copied ? "Copied!" : "Copy JSON"}
              </button>
            )}
          </div>

          <div className="flex-1 flex flex-col overflow-hidden">
            {activeTab === "metadata" && (
              <div className="space-y-6 overflow-y-auto pr-1">
                <div>
                  <h3 className="text-xs uppercase tracking-widest text-muted-foreground font-bold mb-3">
                    Project Info
                  </h3>
                  <table className="w-full text-xs text-left text-muted-foreground">
                    <tbody>
                      <tr className="border-b border-border/40 py-2">
                        <td className="font-semibold text-foreground py-2.5 w-1/3">Project Name</td>
                        <td>{project.name}</td>
                      </tr>
                      <tr className="border-b border-border/40 py-2">
                        <td className="font-semibold text-foreground py-2.5">Duration</td>
                        <td>{duration.toFixed(1)}s</td>
                      </tr>
                      <tr className="border-b border-border/40 py-2">
                        <td className="font-semibold text-foreground py-2.5">Aspect Ratio</td>
                        <td>{project.width} × {project.height} (16:9 HD Canvas)</td>
                      </tr>
                      <tr className="border-b border-border/40 py-2">
                        <td className="font-semibold text-foreground py-2.5">Total Timeline Events</td>
                        <td>{project.events.length} elements (layers)</td>
                      </tr>
                    </tbody>
                  </table>
                </div>

                <div>
                  <h3 className="text-xs uppercase tracking-widest text-muted-foreground font-bold mb-3">
                    Style Catalog Specs
                  </h3>
                  <table className="w-full text-xs text-left text-muted-foreground">
                    <tbody>
                      <tr className="border-b border-border/40 py-2">
                        <td className="font-semibold text-foreground py-2.5 w-1/3">Color Palette</td>
                        <td className="font-mono text-[11px] bg-background px-2 py-0.5 rounded border border-border/40 inline-block text-foreground font-bold">
                          {brief?.palette || "Default (midnight)"}
                        </td>
                      </tr>
                      <tr className="border-b border-border/40 py-2">
                        <td className="font-semibold text-foreground py-2.5">Style Presets</td>
                        <td className="font-mono text-[11px] bg-background px-2 py-0.5 rounded border border-border/40 inline-block text-foreground font-bold">
                          {brief?.style || "Default (modern)"}
                        </td>
                      </tr>
                      <tr className="border-b border-border/40 py-2">
                        <td className="font-semibold text-foreground py-2.5">Layout Selector</td>
                        <td className="font-mono text-[11px] bg-background px-2 py-0.5 rounded border border-border/40 inline-block text-foreground font-bold">
                          {brief?.leftRows || brief?.rightRows ? "Two-Column" : "Single-Column"}
                        </td>
                      </tr>
                      {brief?.flow !== undefined && (
                        <tr className="border-b border-border/40 py-2">
                          <td className="font-semibold text-foreground py-2.5">Data Flow Animations</td>
                          <td className="text-foreground font-semibold">{brief.flow ? "Enabled" : "Disabled"}</td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {isJsonTab && (
              <pre className="flex-1 bg-background text-foreground p-4 rounded-xl text-xs font-mono overflow-auto whitespace-pre-wrap select-text border border-border/80">
                {getCodeContent()}
              </pre>
            )}

            {activeTab === "explanation" && (
              <RenderingExplanation brief={brief} project={project} duration={duration} />
            )}
          </div>
        </section>

        {/* ── Right Column: Visual Timeline & Frame Inspector ─────────── */}
        <section className="w-1/2 flex flex-col h-full border border-border bg-surface-raised rounded-xl p-5 overflow-hidden">
          <div className="border-b border-border/60 pb-3 mb-4">
            <h3 className="text-sm font-bold text-foreground">Timeline Frame Steps</h3>
            <p className="text-xs text-muted-foreground mt-0.5">
              Inspecting {duration.toFixed(1)}s timeline. Click any frame to focus details.
            </p>
          </div>

          {/* Thumbnails grid */}
          <div className="grid grid-cols-4 gap-2.5 overflow-y-auto pb-4 max-h-[200px] border-b border-border/40 pr-1 select-none">
            {frameTimes.map((time) => (
              <FrameThumbnail
                key={time}
                project={project}
                time={time}
                onClick={() => setSelectedTime(time)}
                active={Math.abs(selectedTime - time) < 0.01}
              />
            ))}
          </div>

          {/* Focused frame & event details */}
          <div className="flex-1 mt-4 flex gap-4 overflow-hidden">
            {/* Focus Canvas */}
            <div className="w-1/2 flex flex-col gap-2 overflow-hidden justify-center">
              <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/85">
                Focus Frame at {selectedTime.toFixed(2)}s
              </span>
              <div className="aspect-video w-full rounded-xl overflow-hidden border border-border/80 bg-black/25 flex items-center justify-center p-1">
                <canvas
                  ref={focusCanvasRef}
                  width={project.width || 800}
                  height={project.height || 450}
                  className="w-full h-full object-contain"
                />
              </div>
            </div>

            {/* Event layer checklist */}
            <div className="w-1/2 flex flex-col overflow-hidden">
              <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/85 mb-2.5">
                Active Layers ({activeEvents.length})
              </span>
              <div className="flex-1 overflow-y-auto space-y-2 pr-1 select-text">
                {activeEvents.length === 0 ? (
                  <div className="h-full flex items-center justify-center text-xs text-muted-foreground/60 italic">
                    No active drawing layers at this moment.
                  </div>
                ) : (
                  activeEvents.map((event, idx) => (
                    <div
                      key={`${event.id}-${idx}`}
                      className="p-3 bg-background border border-border/80 rounded-xl space-y-1.5 shadow-xs"
                    >
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-[9px] font-bold uppercase tracking-widest bg-foreground/5 text-foreground px-1.5 py-0.5 rounded border border-border/40">
                          {event.type}
                        </span>
                        <span className="text-[9px] font-mono text-muted-foreground/85">
                          Layer {event.layer}
                        </span>
                      </div>
                      <div className="text-[11px]">
                        <span className="font-semibold text-foreground">ID:</span>{" "}
                        <span className="font-mono text-[10px] bg-foreground/5 px-1 py-0.5 rounded">
                          {event.id}
                        </span>
                      </div>
                      <div className="text-[11px] text-muted-foreground">
                        <span className="font-semibold text-foreground">Timing:</span>{" "}
                        {event.start.toFixed(1)}s – {event.end.toFixed(1)}s
                      </div>
                      {/* Custom context summary based on properties */}
                      {event.type === "text" && (event as any).properties?.text && (
                        <div className="text-[11px] border-t border-border/40 pt-1.5 mt-1">
                          <span className="font-semibold text-foreground">Content:</span>{" "}
                          <span className="italic">"{(event as any).properties.text}"</span>
                        </div>
                      )}
                      {event.type === "shape" && (event as any).properties?.shapeType && (
                        <div className="text-[11px] border-t border-border/40 pt-1.5 mt-1">
                          <span className="font-semibold text-foreground">Shape:</span>{" "}
                          {(event as any).properties.shapeType}
                        </div>
                      )}
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

// ── Root Suspense Wrapper ───────────────────────────────────────────────────
export default function AdvanceDiagnosticsPage() {
  return (
    <Suspense
      fallback={
        <div className="flex h-screen items-center justify-center p-6">
          <p className="text-sm text-muted-foreground">Loading diagnostics view...</p>
        </div>
      }
    >
      <AdvanceWorkspace />
    </Suspense>
  );
}
